### ISSUE TITLE
Unable to Launch on Node 12

### ISSUE THREAD

**Issue by fynncfchen** [Unleash/unleash-proxy#63]
Launch my application with following error:
```
***/node_modules/@unleash/proxy/dist/config.js:44
    return resolveStringToArray(tags)?.map((tag) => {
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (***/node_modules/@unleash/proxy/dist/app.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (***/node_modules/@unleash/proxy/dist/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

I think the issue is causing by the optional chaining, it's not supported on Node v12. (supported from v14)

**Comment by thomasheartman** [comment]
Hey, @fynncfchen 👋🏼  Yeah, you're absolutely right: That appears to be an incompatibility. Thanks for raising this! 

The bad news is that we don't plan on supporting Node 12 (it's maintenance period ends this month), so I'm afraid you're going to need Node 14 or higher to run the Proxy 💁🏼 

The good news is that by raising this issue, you've made us aware that we were missing an `engine` spec in the Proxy's `package.json`. The server specifies that it requires Node 14 or higher, but we must have forgotten to add that to the Proxy. We'll take care of that now.

**Comment by fynncfchen** [comment]
Thanks for answering me! We will consider to upgrade the node version in our side.

**Comment by thomasheartman** [comment]
Of course! Good luck with the upgrade and please don't hesitate to open any more issues if you have questions, issues, or feature requests ☺️
